language: ruby
sudo: false
cache: bundler
branches:
  only: master
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails4.2.gemfile
