language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby
script: "bundle exec rake test"
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails4.1.gemfile
  allow_failures:
    - rvm: 2.0.0
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: 2.1.2
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails4.1.gemfile
