language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby
script: "bundle exec rake test"
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
